<?php

namespace App\Tests\Controller;

use Exception;
use Generator;
use Symfony\Bundle\FrameworkBundle\KernelBrowser;
use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class GreetingControllerTest extends WebTestCase
{

    private static KernelBrowser $client;

    public static function setUpBeforeClass(): void {
        #parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        static::$client = static::createClient();
    }



    // Test for landing page
    public function testPublicUrlsAreOk(): void
    {
//        throw new Exception('bla');
        $client = static::createClient();
        $client->request('GET', '/');

        $this->assertResponseIsSuccessful();
//        $this->assertResponseStatusCodeSame(302);
        //$this->assertResponseRedirects();
//        $this->assertSelectorTextContains('h1', 'Hello World');
    }


    /**
     * @dataProvider provideMethodsAndUrls
     */
    public function testPublicUrlsAreOk_withDataProvider(string $method, string $url): void
    {
        $client = static::createClient();
        $client->request($method, $url);

        $this->assertResponseIsSuccessful();
    }

    public function provideMethodsAndUrls(): Generator {
        yield 'Landing Page' => ['GET', '/'];
        yield ['GET', '/contact'];
        yield ['GET', '/book'];
        yield ['GET', '/book/show'];
        yield ['GET', '/greeting'];
        yield ['GET', '/greeting/Ben'];
    }

}
